apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-classifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-classifier
  template:
    metadata:
      labels:
        app: doc-classifier
    spec:
      containers:
      - name: doc-classifier-service
        image: 'registry.ng.bluemix.net/doc-classifier-service/doc-classifier-service:2018-05-16.0'
        env:
          - name: PORT
            value: "8080"
          - name: VARIABLE
            value: "value"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "1024Mi"
            cpu: "0.75"
        ports:
        - containerPort: 8080
          name: doc-classifier-api