apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dc-msvc-ingress
spec:
  tls:
  - hosts:
    - dc-micro-service.withwatson-std-cluster.us-south.containers.mybluemix.net
    secretName: withwatson-std-cluster
  rules:
  - host: dc-micro-service.withwatson-std-cluster.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /
        backend:
          serviceName: dc-msvc-port-service
          servicePort: 8080